"""
Professioni avanzate (Fase G, quarta tornata): le 39 professioni oltre
le 15 "newbie" (world/professions_newbie.py), estratte verbatim da
info_profs.txt nella scansione esaustiva del sito originale (vedi
research/REPORT.md). A differenza delle newbie, qui l'accesso non e'
libero in creazione personaggio: richiede di soddisfare CONDIZIONI
(livello, razza, cult, allineamento, rating minimo in certe skill,
imprese/"deed" completate).

Copertura: descrizione, attributo primario, modificatori di attributo,
condizioni d'accesso E l'intero albero skill/incantesimo per livello
per tutte le 39 - dati concreti e verificabili, presi punto per punto
dalla fonte.

L'albero per livello di ciascuna professione (chiave "spell_per_livello"
se la fonte usa l'intestazione "SPELLS", "skill_per_livello" se usa
"SKILLS" - la scelta segue esattamente la terminologia della fonte
stessa) e' stato inizialmente costruito a mano solo per Mage e Occult
Master (le uniche due la cui tabella, nel primo passaggio di lettura,
risultava leggibile per intero nonostante il layout a due colonne della
pagina originale). Nella tornata successiva (Fase K, terza tornata) si
e' capito che le due colonne non sono altro che lo spezzamento
tipografico di UN'UNICA lista ordinata (prima meta' a sinistra, seconda
a destra): leggendo il flusso intervallato come semplici coppie
sequenziali (livello, skill) e riordinando per livello si ricostruisce
la tabella originale senza perdita d'informazione, per tutte le
professioni. Verificato con un'estrazione automatica (non manuale) di
research/site_corpus/info_profs.txt, validata a zero differenze contro
le tabelle di Mage (27 livelli) e Occult Master (31 livelli) gia'
costruite a mano, poi applicata alle altre 37. Tre nomi della fonte
erano refusi/varianti di skill gia' registrate altrove e sono stati
ricondotti ad esse invece di essere duplicati: "Anthrapology" ->
anthropology (Journeyman), "Magis Missile" -> magic_missile (Mage,
gia' presente), "Staff" -> staves (Priest of Foxbird). Le 105 skill/
incantesimi ancora mancanti dal registro sono stati aggiunti a
world/skills.py con nome italiano e categoria (inclusa la nuova
categoria "musicale" per gli strumenti del Musicista/Bardo). Un'unica
anomalia della fonte (un livello duplicato nella tabella del Warrior,
livello 21) e' stata unita senza perdita di dati.

Le "imprese" (deed) referenziate dalla fonte (es. "Deed 59 - Something
has awakened within!") sono verificate davvero da valuta_condizioni()
tramite world/imprese.py (Fase K) - titoli reali confermati uno per
uno in info_profs.txt. Tutte e 18 le imprese referenziate hanno ormai
una quest giocabile che le assegna (world/quest.py: "Il Risveglio" per
deed_59, un vero percorso in due tappe; le altre 17 come "achievement"
data-driven a tappa singola, QUESTS_SEMPLICI) - nessuna delle 39
resta piu' irraggiungibile per mancanza del sistema di imprese: quello
che resta e' soltanto soddisfare le altre condizioni (livello/razza/
allineamento/skill) gia' verificate da valuta_condizioni().
"""

ATTRIBUTI_ORDINE = ("str", "int", "wis", "dex", "con", "luck", "cha")

PROFESSIONI_AVANZATE = {
    "adventurer": {
        "nome": "Avventuriero", "nome_originale": "Adventurer",
        "descrizione": "Una persona che desidera esplorare il mondo e scoprire segreti "
                       "nascosti. Focus su abilita' fisiche, con un po' di istruzione.",
        "attributo_primario": "con",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 2, 2, 3, 3, 3, 3))),
        "condizioni": {"skill": {"education": 30, "streetwise": 30, "arkham": 40, "hand_to_hand": 60}},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["climb", "dagger", "dirt_kicking", "haggle", "hide", "kick", "search", "steal", "swim", "whip"],
            2: ["backstab", "german", "hebrew", "sneak"],
            3: ["circle", "handgun", "second_attack"],
            4: ["brawling"],
            5: ["spanish", "survival"],
            6: ["french", "mace"],
            7: ["italian", "parry"],
            8: ["modern_history", "world_geography"],
            9: ["trip", "world_affairs"],
            10: ["fast_healing", "latin"],
            11: ["ancient_geography", "ancient_history"],
            12: ["enhanced_damage", "greek"],
            13: ["disarm"],
            14: ["arabic", "astronomy"],
            15: ["anthropology"],
            16: ["bash"],
            17: ["chinese", "tame"],
            18: ["japanese", "riding"],
            19: ["occult"],
            20: ["bow", "hieroglyphics"],
            21: ["strangle"],
            22: ["traps"],
            24: ["forging"],
            25: ["whip_master"],
            28: ["tailor"],
            31: ["martial_arts"],
            35: ["mayan"],
            45: ["forgery"],
        },
    },
    "arms_master": {
        "nome": "Maestro d'Armi", "nome_originale": "Arms Master",
        "descrizione": "Una persona addestratissima nell'arte del combattimento, armato "
                       "e disarmato. I guerrieri che superano tutti gli altri per abilita' in battaglia.",
        "attributo_primario": "str",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (4, 2, 2, 3, 3, 2, 2))),
        "condizioni": {"livello": 30, "skill": {"streetwise": 50, "ulthar": 60, "sword": 80, "axe": 80}},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["enhanced_damage", "forging", "mace", "parry", "rescue", "second_attack", "shield_block", "strong_grip"],
            2: ["brawling", "disarm", "dual", "fast_healing", "flail", "martial_arts"],
            3: ["spear"],
            4: ["dagger", "third_attack"],
            5: ["climb", "recruit"],
            6: ["riding", "ultra_damage"],
            7: ["strangle", "swim"],
            8: ["whip"],
            9: ["bow"],
            10: ["hide", "polearm"],
            12: ["sword_master"],
            14: ["black_belt"],
            15: ["axe_master", "fourth_attack"],
            17: ["sneak"],
            18: ["mace_master"],
            20: ["lethal_damage"],
            22: ["flail_master"],
            23: ["peek"],
            25: ["sharpen"],
            26: ["spear_master"],
            27: ["dagger_master"],
            30: ["net"],
            34: ["lore"],
            39: ["tracking"],
        },
    },
    "artist": {
        "nome": "Artista", "nome_originale": "Artist",
        "descrizione": "Una persona che ha dedicato la vita allo studio e alla produzione "
                       "di arti creative (pittura, scultura...). Focus educativo e occulto.",
        "attributo_primario": "luck",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (3, 3, 2, 3, 2, 2, 4))),
        "condizioni": {"skill": {"dreaming": 30, "education": 30, "arkham": 40}},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["french", "kick", "modern_history", "spanish", "world_geography"],
            2: ["biology", "dagger", "german", "italian", "theology"],
            3: ["chemistry", "meditation", "physics", "rescue", "world_affairs"],
            4: ["greek", "latin", "old_english", "scrolls"],
            5: ["clairvoyance", "hide", "occult"],
            6: ["astronomy"],
            7: ["ancient_history", "lore"],
            8: ["detect_magic", "sleep", "spell_casting"],
            9: ["ancient_geography", "wands"],
            10: ["detect_hidden", "hebrew"],
            11: ["dream_magic", "ulthar"],
            12: ["manipulation", "scrying"],
            14: ["detect_evil"],
            16: ["detect_invis"],
            18: ["staves"],
            19: ["charm_person"],
            20: ["mask_self"],
            23: ["taumathurgy"],
            25: ["debating"],
            30: ["master_dreamer"],
        },
    },
    "druid": {
        "nome": "Druido", "nome_originale": "Druid",
        "descrizione": "Una persona che ha addestrato i propri poteri magici a toccare e "
                       "manipolare le forze grezze della natura. Un legame profondo con ogni essere vivente.",
        "attributo_primario": "wis",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 3, 3, 1, 2, 3, 2))),
        "condizioni": {"livello": 30, "skill": {"spell_casting": 20, "education": 30, "ulthar": 60},
                       "imprese": ["deed_59", "deed_84"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["elemental_shield", "mace", "natural_magic", "stygian", "whip"],
            2: ["astronomy", "create_spring", "greek", "meditation", "old_english", "scrolls"],
            3: ["ancient_geography", "ancient_history"],
            4: ["control_weather", "parry", "staves", "wands"],
            5: ["climb", "tame"],
            6: ["detect_poison", "faerie_fire"],
            7: ["call_lightning", "detect_magic"],
            8: ["detect_invis", "enhanced_damage", "faerie_fog"],
            9: ["cure_poison", "search"],
            10: ["create_buffet", "dispel_magic", "swim", "way_of_nature"],
            11: ["continual_light", "detect_hidden"],
            12: ["frenzy"],
            13: ["sleep", "strength"],
            14: ["dual"],
            15: ["harden_skin", "water_breathing"],
            16: ["burning_hands", "identify"],
            17: ["lightning_bolt"],
            18: ["riding", "summon_familier"],
            19: ["armor", "scribe"],
            20: ["fly", "tracking"],
            22: ["brew"],
            24: ["whip_master"],
            26: ["chain_lightning"],
            30: ["lightning_breath"],
        },
    },
    "evil_avatar": {
        "nome": "Avatar Malvagio", "nome_originale": "Evil Avatar",
        "descrizione": "Un sacerdote/sacerdotessa che ha elevato la propria coscienza fino a "
                       "diventare incarnazione mortale della divinita' che venera, al servizio "
                       "dell'oscurita' e del male.",
        "attributo_primario": "wis",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 2, 4, 2, 2, 3, 3))),
        "condizioni": {"livello": 30, "allineamento": (-1000, -500),
                       "skill": {"education": 80, "theology": 80}, "imprese": ["deed_86"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["dagger", "protection_good", "second_attack", "whip"],
            2: ["blindness", "cause_light", "know_alignment"],
            3: ["cause_serious", "enhanced_damage"],
            4: ["meditation", "poison"],
            5: ["frenzy"],
            6: ["demonfire", "plague"],
            7: ["weaken"],
            8: ["create_potion"],
            10: ["manipulation"],
            11: ["cthonic"],
            12: ["cause_critical"],
            14: ["stygian"],
            15: ["chaos_magic", "curse"],
            17: ["create_food"],
            18: ["create_water", "mute"],
            19: ["scrying"],
            20: ["envenom"],
            22: ["lesser_possession"],
            23: ["mental_magic"],
            24: ["third_attack"],
            25: ["harm"],
            27: ["haste"],
            30: ["whip_master"],
            32: ["age"],
            35: ["aura"],
            40: ["gate"],
            45: ["protective_magic"],
            48: ["divine_magic"],
        },
    },
    "forest_ghost": {
        "nome": "Spettro della Foresta", "nome_originale": "Forest Ghost",
        "descrizione": "Uno Zoog esperto nel sopravvivere alle foreste oscure delle "
                       "Dreamlands. Buona base di abilita' fisiche.",
        "attributo_primario": "dex",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 2, 3, 3, 2, 3, 1))),
        "condizioni": {"razza": "zoog",
                       "skill": {"education": 20, "hide": 30, "sneak": 30, "dreamlands": 40, "streetwise": 40}},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["climb", "cthonic", "dagger", "dirt_kicking", "hide", "kick", "mace", "tame", "search", "steal", "swim"],
            2: ["backstab", "parry", "sneak", "spanish"],
            3: ["circle", "martial_arts", "second_attack", "tailor"],
            4: ["haggle", "spear", "tracking"],
            5: ["detection", "rotate"],
            6: ["italian", "sword"],
            7: ["bow", "enhanced_damage"],
            8: ["peek", "romany"],
            9: ["pick_lock", "traps"],
            10: ["polish"],
            11: ["fast_healing"],
            12: ["accounting"],
            14: ["third_attack"],
            15: ["greek"],
            16: ["occult"],
            17: ["ultra_damage"],
            18: ["latin"],
            19: ["meditation"],
            20: ["lore"],
        },
    },
    "gangster": {
        "nome": "Gangster", "nome_originale": "Gangster",
        "descrizione": "Una persona salita a una posizione di autorita' e potere nel "
                       "sottobosco criminale. Focus fisico con un po' di istruzione.",
        "attributo_primario": "dex",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (3, 2, 2, 3, 2, 1, 2))),
        "condizioni": {"skill": {"handgun": 30, "arkham": 40, "hand_to_hand": 60, "streetwise": 60}},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["climb", "dagger", "dirt_kicking", "haggle", "hide", "kick", "mace", "search", "steal", "swim"],
            2: ["backstab", "german", "parry", "sneak", "strangle"],
            3: ["circle", "handgun"],
            4: ["brawling", "polish"],
            5: ["italian", "second_attack"],
            6: ["enhanced_damage", "world_affairs"],
            7: ["shield_block", "trip"],
            8: ["fast_healing"],
            9: ["sword"],
            10: ["accounting", "detection"],
            11: ["submachinegun"],
            12: ["sharpen"],
            13: ["chemistry"],
            14: ["rotate"],
            15: ["bash"],
            16: ["world_geography"],
            17: ["chinese"],
            18: ["modern_history"],
            19: ["gun"],
            20: ["third_attack"],
            22: ["gambling", "ultra_damage"],
            25: ["dagger_master"],
            27: ["forgery"],
            30: ["intimidate"],
            33: ["explosives"],
            36: ["assassinate"],
        },
    },
    "ghost_walker": {
        "nome": "Camminatore Spettrale", "nome_originale": "Ghost Walker",
        "descrizione": "Uno Zoog che ha addestrato i propri poteri magici a un livello "
                       "superiore, toccando i poteri dell'universo. Focus su magia, occultismo e incantesimi.",
        "attributo_primario": "int",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (1, 2, 3, 2, 2, 3, 1))),
        "condizioni": {"razza": "zoog", "skill": {"occult": 30, "dreamlands": 40, "education": 60},
                       "imprese": ["deed_59"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["cthonic", "dagger", "french", "latin", "spanish", "spell_casting", "theology", "water_breathing"],
            2: ["greek", "manipulation", "meditation", "old_english", "scrolls", "spear"],
            3: ["ancient_geography", "ancient_history", "armor", "astronomy"],
            4: ["bless", "staves", "wands"],
            5: ["hebrew"],
            6: ["faerie_fire", "ventriloquate"],
            7: ["detect_magic", "magic_missile"],
            8: ["detect_invis", "faerie_fog"],
            9: ["invis", "mute"],
            10: ["dispel_magic", "remove_invis"],
            11: ["continual_light", "detect_hidden"],
            12: ["locate_object"],
            13: ["sleep", "strength"],
            14: ["cancellation"],
            15: ["charm_person", "enchant_armor", "lesser_possession"],
            16: ["burning_hands", "identify"],
            17: ["brand"],
            18: ["enchant_weapon"],
            19: ["shield"],
            20: ["fly", "lore"],
            25: ["taumathurgy"],
            30: ["greater_possession"],
        },
    },
    "good_avatar": {
        "nome": "Avatar Benevolo", "nome_originale": "Good Avatar",
        "descrizione": "Un sacerdote/sacerdotessa che ha elevato la propria coscienza fino a "
                       "diventare incarnazione mortale della divinita' che venera, al servizio "
                       "della luce e della vita.",
        "attributo_primario": "wis",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 2, 4, 2, 2, 3, 3))),
        "condizioni": {"livello": 30, "allineamento": (500, 1000),
                       "skill": {"education": 80, "theology": 80}, "imprese": ["deed_85"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["dagger", "mace", "protection_evil", "second_attack"],
            2: ["flail", "hebrew", "know_alignment"],
            3: ["cure_serious", "enhanced_damage", "elemental_shield"],
            4: ["armor", "meditation"],
            5: ["create_food", "gaelic"],
            6: ["create_water", "cure_disease"],
            7: ["fast_healing"],
            8: ["create_potion"],
            10: ["identify"],
            11: ["cthonic"],
            12: ["cure_critical"],
            14: ["atlantean"],
            15: ["calm", "remove_curse"],
            17: ["create_buffet"],
            18: ["create_spring", "harden_skin"],
            19: ["scrying"],
            20: ["earthquake"],
            22: ["lesser_possession"],
            23: ["holy_word"],
            24: ["disarm"],
            25: ["heal"],
            27: ["protective_magic"],
            29: ["youth"],
            30: ["mace_master"],
            35: ["ultra_damage"],
            37: ["aura"],
            38: ["gate"],
            40: ["mass_healing"],
            42: ["greater_possession"],
            45: ["divine_magic"],
        },
    },
    "journeyman": {
        "nome": "Apprendista Provetto", "nome_originale": "Journeyman",
        "descrizione": "Una persona con esperienza moderata che ha continuato a studiare un "
                       "mestiere e inizia a raggiungere l'eccellenza. Focus fisico con un po' di occultismo.",
        "attributo_primario": "dex",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (3, 2, 2, 3, 2, 2, 2))),
        "condizioni": {"skill": {"education": 30, "streetwise": 30, "arkham": 40}, "imprese": ["deed_60"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["accounting", "climb", "haggle", "hide", "search", "sneak"],
            2: ["detection", "forging", "german", "swim"],
            3: ["chemistry", "physics", "pick_lock"],
            4: ["biology", "parry"],
            5: ["dagger", "occult"],
            6: ["greek"],
            7: ["latin", "world_affairs"],
            8: ["meditation", "world_geography", "tailor"],
            9: ["sharpen", "spell_casting"],
            10: ["ancient_geography"],
            11: ["refresh", "spear"],
            12: ["detect_magic"],
            13: ["brand"],
            14: ["ancient_history", "detect_poison"],
            15: ["continual_light"],
            16: ["detect_hidden"],
            17: ["atlantean", "identity"],
            18: ["pass_door"],
            19: ["poison"],
            21: ["goldsmith"],
            23: ["enchant_weapon"],
            25: ["enchant_armor"],
            29: ["taumathurgy"],
        },
    },
    "mage": {
        "nome": "Mago", "nome_originale": "Mage",
        "descrizione": "Una persona che ha sviluppato i propri poteri magici a un livello "
                       "superiore, toccando i poteri dell'universo. Focus su magia, occultismo e incantesimi.",
        "attributo_primario": "int",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (1, 3, 2, 2, 2, 2, 2))),
        "condizioni": {"skill": {"occult": 30, "ulthar": 40, "education": 60}, "imprese": ["deed_59"]},
        # Una delle due tabelle costruite a mano per prime (con
        # occult_master), poi usate per validare a zero differenze
        # l'estrazione automatica applicata alle altre 37 - vedi
        # docstring del modulo.
        "spell_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["dagger", "french", "latin", "spanish", "theology"],
            2: ["greek", "meditation", "old_english", "scrolls", "spear"],
            3: ["ancient_geography", "ancient_history", "astronomy", "spell_casting"],
            4: ["armor", "staves", "wands"],
            5: ["hebrew"],
            6: ["faerie_fire", "ventriloquate"],
            7: ["detect_magic", "magic_missile"],
            8: ["detect_invis", "faerie_fog"],
            9: ["invis", "mute"],
            10: ["dispel_magic", "remove_invis"],
            11: ["continual_light", "detect_hidden"],
            12: ["create_food"],
            13: ["sleep", "strength"],
            14: ["cancellation"],
            15: ["charm_person", "debating", "enchant_armor"],
            16: ["burning_hands", "identify"],
            17: ["brand"],
            18: ["enchant_weapon"],
            19: ["lesser_possession", "shield"],
            20: ["fly", "lore"],
            22: ["climb"],
            23: ["scribe"],
            25: ["swim"],
            28: ["taumathurgy"],
            31: ["elemental_shield"],
            35: ["greater_possession"],
        },
    },
    "master_of_the_deep": {
        "nome": "Maestro degli Abissi", "nome_originale": "Master of the Deep",
        "descrizione": "Un Profondo che ha scelto la via del guerriero: l'elite dei "
                       "combattenti Profondi, assassini e signori della guerra.",
        "attributo_primario": "str",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (4, 2, 2, 2, 3, 2, 1))),
        "condizioni": {"razza": "deep_one", "livello": 30,
                       "skill": {"arkham": 20, "innsmouth": 60, "dagger": 80, "spear": 80}},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["enhanced_damage", "parry", "polearm", "rescue", "second_attack", "shield_block", "strong_grip"],
            2: ["brawling", "disarm", "dual", "fast_healing", "flail", "martial_arts"],
            3: ["mace"],
            4: ["hide", "third_attack"],
            5: ["handgun", "recruit"],
            6: ["ultra_damage"],
            7: ["climb"],
            8: ["sword"],
            10: ["dagger_master", "sneak"],
            12: ["spear_master"],
            14: ["black_belt"],
            15: ["axe_master", "fourth_attack"],
            16: ["spell_casting"],
            17: ["create_water", "gun"],
            18: ["polearm_master"],
            19: ["create_spring"],
            20: ["lethal_damage"],
            21: ["mask_self"],
            22: ["flail_master"],
            23: ["peek"],
            24: ["japanese"],
            25: ["sharpen"],
            26: ["sword_master"],
            27: ["submachinegun"],
            30: ["lore"],
            35: ["stygian"],
            40: ["marksman"],
        },
    },
    "medic": {
        "nome": "Medico", "nome_originale": "Medic",
        "descrizione": "Una persona dedita all'arte della guarigione. Addestramento in "
                       "abilita' mediche e accademiche, oltre a qualche abilita' di combattimento avanzata.",
        "attributo_primario": "int",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 3, 3, 3, 2, 2, 3))),
        "condizioni": {"skill": {"biology": 30, "arkham": 40, "education": 60}, "imprese": ["deed_56"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["dissertation", "french", "german", "latin", "spanish"],
            2: ["accounting", "chemistry", "dagger", "italian"],
            3: ["fast_healing", "modern_history"],
            4: ["debating"],
            5: ["theology"],
            6: ["bandage"],
            7: ["physics", "world_affairs"],
            8: ["ancient_history"],
            9: ["enhanced_damage", "parry"],
            10: ["backstab", "greek"],
            11: ["swim", "sword"],
            12: ["tailor"],
            13: ["climb"],
            14: ["astronomy"],
            15: ["anthropology"],
            16: ["psychology"],
            18: ["occult"],
            20: ["disarm"],
            35: ["surgery"],
        },
    },
    "mentalist": {
        "nome": "Mentalista", "nome_originale": "Mentalist",
        "descrizione": "Una sorta di mago o occultista il cui addestramento gli permette di "
                       "tessere magia con la sola mente. Incantesimi perlopiu' mentali e difficili.",
        "attributo_primario": "wis",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (1, 3, 2, 2, 1, 3, 3))),
        "condizioni": {"skill": {"occult": 40, "ulthar": 40, "education": 70}, "imprese": ["deed_59"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["dagger", "latin", "meditation", "whip"],
            2: ["chinese", "old_english", "scrolls"],
            3: ["arabic", "astronomy", "japanese", "spell_casting"],
            4: ["know_alignment"],
            5: ["hebrew"],
            6: ["clairvoyance", "ventriloquate"],
            7: ["detect_hidden", "vocalize"],
            8: ["detect_invis", "frenzy"],
            9: ["mute", "weaken"],
            10: ["blindness", "way_of_the_duellant"],
            11: ["continual_light", "sleep"],
            12: ["remove_fear"],
            13: ["manipulation", "psychic_anchor"],
            14: ["calm", "charm_person", "lesser_possession"],
            15: ["debating"],
            16: ["identify"],
            18: ["body_control"],
            20: ["lore", "strength"],
            22: ["climb"],
            23: ["mental_magic"],
            25: ["swim"],
            35: ["mask_self"],
        },
    },
    "migo_surgeon": {
        "nome": "Chirurgo Mi-Go", "nome_originale": "Migo Surgeon",
        "descrizione": "Un Mi-Go esperto che si sforza di trovare materiali grezzi "
                       "accettabili. Un medico capace e un killer spietato.",
        "attributo_primario": "int",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 3, 3, 3, 2, 2, 2))),
        "condizioni": {"razza": "mi_go", "skill": {"yuggoth": 40, "bandage": 60, "education": 70}},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["climb", "control_weather", "handgun", "hebrew", "meditation", "modern_history", "world_geography"],
            2: ["cure_light", "detection", "gaelic", "search"],
            3: ["cthonic", "envenom", "fast_healing"],
            4: ["martial_arts"],
            5: ["lore", "parry"],
            6: ["brew"],
            7: ["cure_serious", "spear"],
            8: ["second_attack"],
            9: ["polearm"],
            10: ["enhanced_damage", "plague"],
            11: ["scribe"],
            12: ["forging", "psychology"],
            13: ["invis"],
            14: ["shocking_grasp"],
            15: ["surgery"],
            16: ["tracking"],
            17: ["body_control"],
            19: ["debating"],
            20: ["necromancy"],
            22: ["regeneration"],
            25: ["third_attack"],
            27: ["interrogate"],
            31: ["youth"],
            33: ["strangle"],
            35: ["biotechnology"],
            40: ["age"],
        },
    },
    "musician": {
        "nome": "Musicista", "nome_originale": "Musician",
        "descrizione": "Una persona che ha dedicato la vita allo studio e all'esecuzione "
                       "della musica: ogni tipo di strumento, e persino il segreto potere delle incantagioni.",
        "attributo_primario": "dex",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (1, 2, 3, 3, 2, 1, 3))),
        "condizioni": {"skill": {"education": 50}},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["french", "music"],
            2: ["singing"],
            4: ["italian"],
            5: ["piano"],
            7: ["percussion"],
            9: ["old_english"],
            13: ["strings"],
            16: ["brass"],
            19: ["flute"],
            24: ["occult"],
            30: ["organ"],
            35: ["spell_casting"],
            36: ["voice"],
        },
    },
    "necromancer": {
        "nome": "Negromante", "nome_originale": "Necromancer",
        "descrizione": "Una persona che ha addestrato i propri poteri magici per risvegliare "
                       "e comandare i morti. Focus su magia oscura e incantesimi.",
        "attributo_primario": "int",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 3, 2, 2, 1, 3, 1))),
        "condizioni": {"allineamento": (-1000, -500),
                       "skill": {"education": 40, "ulthar": 40, "occult": 60}, "imprese": ["deed_59"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["french", "latin", "spanish", "theology", "whip"],
            2: ["greek", "meditation", "old_english", "scrolls", "spear"],
            3: ["ancient_geography", "ancient_history", "astronomy", "spell_casting"],
            4: ["armor", "staves", "wands"],
            5: ["hebrew"],
            6: ["cthonic", "faerie_fire"],
            7: ["detect_magic", "magic_missile"],
            8: ["blindness", "poison"],
            9: ["mute"],
            10: ["chill_touch", "weaken"],
            11: ["continual_light", "invis"],
            12: ["mental_magic"],
            13: ["sleep", "strength"],
            14: ["cancellation", "manipulation"],
            15: ["curse", "frenzy"],
            16: ["burning_hands"],
            17: ["energy_drain"],
            18: ["necromancy"],
            19: ["plague"],
            20: ["acid_blast", "lore"],
            22: ["scribe"],
        },
    },
    "occult_master": {
        "nome": "Maestro dell'Occulto", "nome_originale": "Occult Master",
        "descrizione": "Una persona progredita al livello successivo degli studi occulti: "
                       "skill arcane avanzate e incantesimi, oltre a qualche abilita' fisica e di combattimento.",
        "attributo_primario": "int",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 4, 3, 2, 2, 2, 2))),
        "condizioni": {"livello": 30,
                       "skill": {"arkham": 60, "education": 80, "spell_casting": 80, "occult": 95},
                       "imprese": ["deed_59", "deed_83"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["clairvoyance", "cthonic", "enhanced_damage", "fast_healing", "lesser_possession", "second_attack"],
            2: ["blindness", "create_food"],
            3: ["sword", "water_breathing"],
            4: ["create_spring"],
            5: ["word_of_recall"],
            6: ["scribe", "stygian"],
            7: ["harden_skin"],
            8: ["channeling"],
            10: ["debating", "negate_alignment"],
            12: ["call_lightning"],
            13: ["elemental_shield"],
            14: ["calm"],
            15: ["mass_invis"],
            16: ["fireball"],
            17: ["greater_possession", "summon_familier"],
            18: ["spell_mastery"],
            19: ["teleport"],
            20: ["haste"],
            22: ["dagger_master"],
            23: ["pass_door"],
            25: ["absorb_magic"],
            26: ["ritual_mastery"],
            27: ["fire_breath"],
            29: ["frost_breath"],
            32: ["taumathurgy"],
            35: ["summon"],
            39: ["portal"],
            44: ["teach"],
            45: ["voodoo"],
            50: ["mask_self"],
            85: ["elder_magic"],
        },
    },
    "occultist": {
        "nome": "Occultista", "nome_originale": "Occultist",
        "descrizione": "Una persona i cui poteri magici si sono risvegliati in qualche modo, "
                       "toccando i poteri dell'universo. Focus su conoscenza magica e arcana, incantesimi inclusi.",
        "attributo_primario": "int",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 4, 2, 2, 2, 3, 2))),
        "condizioni": {"skill": {"occult": 30, "arkham": 40, "education": 60}, "imprese": ["deed_59"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["dagger", "french", "german", "latin", "modern_history", "theology", "world_geography"],
            2: ["greek", "meditation", "old_english", "scrolls"],
            3: ["ancient_geography", "ancient_history", "astronomy"],
            4: ["hebrew", "staves", "wands"],
            5: ["armor", "spell_casting"],
            6: ["faerie_fire", "ventriloquate"],
            7: ["detect_magic", "magic_missile"],
            8: ["detect_invis", "faerie_fog"],
            9: ["invis", "mute"],
            10: ["dispel_magic", "remove_invis"],
            11: ["continual_light", "detect_hidden"],
            12: ["locate_object"],
            13: ["sleep", "strength"],
            14: ["cancellation"],
            15: ["charm_person", "enchant_armor"],
            16: ["burning_hands", "identify"],
            17: ["brand"],
            18: ["enchant_weapon", "scribe"],
            19: ["shield"],
            20: ["fly", "lore"],
            22: ["climb"],
            24: ["lesser_possession"],
            25: ["clairvoyance"],
            27: ["swim"],
            30: ["taumathurgy"],
            35: ["channeling"],
        },
    },
    "officer": {
        "nome": "Ufficiale", "nome_originale": "Officer",
        "descrizione": "Un uomo o una donna al comando di un'unita' militare: servono "
                       "forma fisica, capacita' di comando e leadership.",
        "attributo_primario": "str",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (3, 2, 3, 2, 3, 3, 3))),
        "condizioni": {"livello": 30,
                       "skill": {"streetwise": 30, "arkham": 60, "education": 70, "handgun": 80},
                       "imprese": ["deed_81"]},
        "skill_per_livello": {
            0: ["dodge", "english"],
            1: ["enhanced_damage", "hand_to_hand", "handgun", "parry", "riding", "sword"],
            2: ["fast_healing", "recruit"],
            3: ["german", "second_attack", "world_geography"],
            4: ["world_affairs"],
            5: ["strangle"],
            6: ["envenom"],
            7: ["french", "italian"],
            8: ["dagger_master"],
            9: ["accounting"],
            10: ["backstab"],
            11: ["tracking"],
            12: ["explosives", "ultra_damage"],
            13: ["marksman"],
            14: ["sharpen"],
            15: ["blackjack", "interrogate"],
            16: ["third_attack"],
            18: ["intimidate"],
            19: ["black_belt"],
            21: ["self_discipline"],
            23: ["lethal_damage"],
            30: ["leadership"],
            38: ["tactics"],
            45: ["sniper"],
            55: ["fourth_attack"],
        },
    },
    "paladin": {
        "nome": "Paladino", "nome_originale": "Paladin",
        "descrizione": "Una persona addestrata nelle arti del combattimento, armato e "
                       "disarmato, che usa le proprie abilita' al servizio del bene. Retto e legale, "
                       "ma non necessariamente gentile.",
        "attributo_primario": "wis",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (3, 2, 2, 2, 3, 2, 4))),
        "condizioni": {"livello": 30, "allineamento": (200, 1000),
                       "skill": {"education": 50, "polearm": 60, "sword": 80}, "imprese": ["deed_9071"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["old_english", "parry", "polish", "riding", "second_attack", "shield_block"],
            2: ["ancient_history", "dual", "enhanced_damage", "gaelic"],
            3: ["rescue", "spell_casting"],
            4: ["create_food", "create_water"],
            5: ["fast_healing", "self_discipline", "word_of_recall"],
            6: ["latin"],
            7: ["armor"],
            8: ["greek"],
            9: ["cure_light"],
            10: ["bless", "ultra_damage"],
            11: ["detect_evil"],
            12: ["cthonic"],
            13: ["protection_evil", "recruit"],
            14: ["know_alignment"],
            15: ["dispel_evil", "third_attack"],
            17: ["cure_serious"],
            18: ["sword_master"],
            19: ["refresh"],
            20: ["atlantean"],
            22: ["remove_curse"],
            23: ["polearm_master"],
            24: ["frenzy"],
            26: ["strength"],
            27: ["lore"],
            29: ["holy_word"],
            30: ["stygian"],
            32: ["intimidate"],
            35: ["enchant_weapon"],
            40: ["protective_magic"],
        },
    },
    "policeman": {
        "nome": "Poliziotto", "nome_originale": "Policeman",
        "descrizione": "Una persona addestrata all'uso delle armi e all'applicazione della "
                       "legge, responsabile di mantenere l'ordine. Focus fisico, con abilita' educative incluse.",
        "attributo_primario": "con",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (3, 1, 2, 2, 3, 2, 1))),
        "condizioni": {"skill": {"education": 30, "streetwise": 30, "arkham": 40}},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["brawling", "dagger", "hide", "kick", "parry", "search", "swim"],
            2: ["german", "handgun", "sneak", "trip"],
            3: ["detection", "gun", "second_attack", "shield_block"],
            4: ["climb", "disarm", "enhanced_damage"],
            5: ["pick_lock", "polish"],
            6: ["italian"],
            7: ["bash", "martial_arts"],
            8: ["haggle", "latin"],
            9: ["fast_healing"],
            10: ["accounting", "strong_grip"],
            11: ["rescue"],
            12: ["rotate"],
            13: ["circle"],
            14: ["dual"],
            15: ["riding", "world_affairs"],
            17: ["submachinegun"],
            18: ["third_attack"],
            20: ["interrogate"],
            22: ["ultra_damage"],
            26: ["marksman"],
        },
    },
    "postgraduate": {
        "nome": "Laureato Specializzando", "nome_originale": "Postgraduate",
        "descrizione": "Una persona che continua a studiare all'universita' dopo la laurea. "
                       "Forte focus su abilita' accademiche.",
        "attributo_primario": "int",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 3, 3, 2, 2, 3, 3))),
        "condizioni": {"skill": {"arkham": 40, "education": 60}, "imprese": ["deed_56"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["debating", "dissertation", "french", "german", "spanish"],
            2: ["biology", "chemistry", "italian", "physics", "world_geography"],
            3: ["modern_history", "old_english"],
            4: ["hebrew", "world_affairs"],
            5: ["polish", "riding"],
            6: ["bow", "latin"],
            7: ["fast_healing", "romany"],
            8: ["ancient_history"],
            9: ["accounting", "ancient_geography"],
            10: ["gaelic", "greek"],
            11: ["parry", "sword"],
            12: ["arabic"],
            13: ["geology"],
            14: ["astronomy"],
            15: ["anthropology"],
            16: ["chinese"],
            17: ["japanese"],
            18: ["occult"],
            19: ["disarm"],
            20: ["hieroglyphics"],
        },
    },
    "priest_of_bast": {
        "nome": "Sacerdote di Bast", "nome_originale": "Priest of Bast",
        "descrizione": "Una persona che ha dedicato la vita al servizio della Dea Bast. "
                       "Focus su conoscenza religiosa e incantesimi.",
        "attributo_primario": "wis",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 2, 3, 3, 2, 4, 2))),
        "condizioni": {"skill": {"theology": 30, "ulthar": 40, "education": 60}, "imprese": ["deed_9004"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["ancient_geography", "ancient_history", "latin", "theology"],
            2: ["hide", "old_english", "scrolls", "spanish"],
            3: ["astronomy", "spear"],
            4: ["cthonic", "staves", "wands"],
            5: ["dagger", "parry"],
            7: ["bless", "spell_casting"],
            8: ["shield_block"],
            9: ["sneak"],
            10: ["armor", "tame"],
            11: ["cure_light"],
            12: ["second_attack"],
            13: ["detect_hidden"],
            14: ["refresh"],
            15: ["cure_blindness"],
            16: ["brew", "detect_invis"],
            17: ["cure_serious"],
            18: ["invis"],
            19: ["haste"],
            20: ["clerical_magic"],
            22: ["debating"],
        },
    },
    "priest_of_dagon": {
        "nome": "Sacerdote di Dagon", "nome_originale": "Priest of Dagon",
        "descrizione": "Una persona che ha dedicato la vita al servizio del Dio Dagon. "
                       "Focus su conoscenza religiosa e incantesimi.",
        "attributo_primario": "wis",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (3, 2, 3, 2, 3, 1, 1))),
        "condizioni": {"skill": {"theology": 30, "ulthar": 40, "education": 60}, "imprese": ["deed_1319"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["arabic", "atlantean", "japanese", "modern_history", "swim", "theology", "world_geography"],
            2: ["gaelic", "greek", "meditation", "scrolls"],
            3: ["ancient_geography", "ancient_history", "cthonic"],
            4: ["hebrew", "staves", "wands"],
            5: ["parry", "spear"],
            6: ["fast_healing"],
            7: ["create_water", "spell_casting"],
            8: ["shield_block"],
            9: ["water_breathing"],
            10: ["curse", "detect_good"],
            11: ["vision"],
            12: ["brew", "second_attack"],
            13: ["protection_good"],
            14: ["shocking_grasp"],
            15: ["control_weather"],
            16: ["cure_light"],
            17: ["mask_self"],
            18: ["poison"],
            19: ["plague"],
            20: ["regeneration"],
        },
    },
    "priest_of_foxbird": {
        "nome": "Sacerdote di Foxbird", "nome_originale": "Priest of Foxbird",
        "descrizione": "Un uomo o una donna che ha dedicato la vita al servizio di Foxbird, "
                       "il Dio della Magia. Focus su conoscenza magica e incantesimi.",
        "attributo_primario": "int",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 4, 4, 2, 2, 2, 3))),
        "condizioni": {"livello": 30, "imprese": ["deed_4316"]},
        "skill_per_livello": {
            0: ["english", "spell_casting"],
            1: ["bless", "magic_missile", "shield", "teach"],
            2: ["german", "greek", "refresh", "scrolls", "staves"],
            3: ["ancient_history", "cthonic", "latin", "lore", "wands"],
            4: ["meditation", "natural_magic"],
            5: ["fly", "lightning_bolt"],
            6: ["old_english", "staves"],
            7: ["create_food", "create_water"],
            8: ["clairvoyance", "create_spring"],
            9: ["armor", "cause_light", "colour_spray", "haste"],
            10: ["invis", "magefire", "recall", "scrying"],
            11: ["fireball"],
            12: ["holy_word"],
            13: ["dream_magic"],
            14: ["faerie_fire"],
            15: ["body_control"],
            16: ["dispel_magic", "pass_door"],
            17: ["chain_lightning", "locate_object"],
            18: ["channeling"],
            19: ["absorb_magic"],
            20: ["spell_mastery"],
            21: ["age", "youth"],
            22: ["ritual_mastery"],
            23: ["enchant_weapon"],
            24: ["teleport"],
            25: ["cancellation"],
            50: ["elder_magic"],
        },
    },
    "priest_of_marduk": {
        "nome": "Sacerdote di Marduk", "nome_originale": "Priest of Marduk",
        "descrizione": "Una persona che ha dedicato la vita al servizio del Dio Marduk. "
                       "Focus su conoscenza religiosa e incantesimi.",
        "attributo_primario": "wis",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 2, 3, 2, 2, 2, 4))),
        "condizioni": {"skill": {"theology": 30, "arkham": 40, "education": 60}, "imprese": ["deed_57"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["french", "german", "latin", "modern_history", "theology", "world_geography"],
            2: ["greek", "meditation", "old_english", "scrolls"],
            3: ["ancient_geography", "ancient_history", "astronomy"],
            4: ["hebrew", "staves", "wands"],
            5: ["flail", "parry"],
            6: ["fast_healing"],
            7: ["bless", "spell_casting"],
            8: ["shield_block"],
            9: ["detect_evil"],
            10: ["armor", "debating"],
            11: ["cure_light"],
            12: ["brew", "second_attack"],
            13: ["protection_evil"],
            14: ["refresh"],
            15: ["bow", "cure_blindness"],
            16: ["cure_poison"],
            17: ["cure_serious"],
            18: ["remove_fear"],
            19: ["dispel_evil"],
            20: ["clerical_magic"],
            22: ["tame"],
            24: ["clairvoyance"],
            26: ["elemental_shield"],
            34: ["elemental_combat"],
        },
    },
    "priest_of_shub_niggurath": {
        "nome": "Sacerdote di Shub-Niggurath", "nome_originale": "Priest of Shub-Niggurath",
        "descrizione": "Una persona che ha dedicato la vita al servizio del Dio "
                       "Shub-Niggurath. Focus su conoscenza religiosa e incantesimi.",
        "attributo_primario": "wis",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 2, 3, 2, 3, 2, 2))),
        "condizioni": {"skill": {"theology": 30, "arkham": 40, "education": 60}, "imprese": ["deed_1329"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["french", "german", "latin", "modern_history", "theology", "world_geography"],
            2: ["greek", "meditation", "old_english", "scrolls"],
            3: ["ancient_geography", "ancient_history", "astronomy"],
            4: ["hebrew", "staves", "wands"],
            5: ["flail", "parry"],
            6: ["fast_healing"],
            7: ["faerie_fire", "spell_casting"],
            8: ["shield_block"],
            9: ["detect_good"],
            10: ["armor", "debating"],
            11: ["cause_light"],
            12: ["brew", "second_attack"],
            13: ["protection_good"],
            14: ["refresh"],
            15: ["blindness"],
            16: ["poison"],
            17: ["cause_serious"],
            18: ["faerie_fog", "manipulation"],
            19: ["dispel_good"],
            20: ["charm_person"],
            23: ["lesser_protection"],
        },
    },
    "priest_of_thanatos": {
        "nome": "Sacerdote di Thanatos", "nome_originale": "Priest of Thanatos",
        "descrizione": "Una persona che ha dedicato la vita al servizio di Thanatos e al "
                       "ciclo naturale della vita. Equilibrio tra abilita' mondane e conoscenza mistica.",
        "attributo_primario": "wis",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 2, 3, 2, 3, 2, 1))),
        "condizioni": {"livello": 30, "cult": "thanatos",
                       "skill": {"theology": 50, "education": 60}, "imprese": ["deed_3796"]},
        "skill_per_livello": {
            0: ["latin"],
            1: ["theology"],
            2: ["survival"],
            3: ["meditation", "spell_casting"],
            4: ["axe", "bless"],
            6: ["astronomy", "greek"],
            7: ["protection_evil", "protection_good"],
            8: ["chill_touch", "scrying"],
            9: ["brew", "negate_alignment", "polearm"],
            10: ["protective_magic"],
            11: ["biology", "strong_grip"],
            12: ["cure_disease"],
            14: ["enhanced_damage", "way_of_the_duellant"],
            15: ["plague"],
            16: ["remove_invis"],
            17: ["psychology"],
            18: ["bandage"],
            19: ["natural_magic", "polearm_master"],
            23: ["ultra_damage"],
            25: ["necromancy"],
            32: ["lethal_damage"],
            70: ["elder_magic"],
        },
    },
    "priest_of_yog_sothoth": {
        "nome": "Sacerdote di Yog-Sothoth", "nome_originale": "Priest of Yog-Sothoth",
        "descrizione": "Una persona che ha dedicato la vita al servizio del Dio "
                       "Yog-Sothoth. Focus su conoscenza religiosa e incantesimi.",
        "attributo_primario": "wis",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 2, 3, 3, 2, 2, 1))),
        "condizioni": {"skill": {"theology": 30, "arkham": 40, "education": 60}, "imprese": ["deed_1309"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["cthonic", "french", "modern_history", "polish", "theology", "world_geography"],
            2: ["latin", "meditation", "old_english", "scrolls"],
            3: ["ancient_geography", "ancient_history", "astronomy"],
            4: ["hebrew", "staves", "wands"],
            5: ["parry", "whip"],
            6: ["fast_healing"],
            7: ["spell_casting"],
            8: ["shield_block"],
            9: ["detect_good"],
            10: ["armor", "curse"],
            11: ["cause_light"],
            12: ["brew", "second_attack"],
            13: ["protection_good"],
            14: ["plague"],
            15: ["blindness"],
            16: ["poison"],
            17: ["cause_serious"],
            19: ["fly"],
            20: ["haste"],
        },
    },
    "private_investigator": {
        "nome": "Investigatore Privato", "nome_originale": "Private Investigator",
        "descrizione": "Un investigatore scalcinato in stile Raymond Chandler.",
        "attributo_primario": "con",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 2, 4, 2, 4, 4, 2))),
        "condizioni": {"livello": 30,
                       "skill": {"arkham": 60, "search": 50, "streetwise": 80, "education": 50},
                       "imprese": ["deed_82"]},
        "skill_per_livello": {
            0: ["hand_to_hand", "dodge", "english"],
            1: ["handgun", "search"],
            2: ["haggle"],
            3: ["hide"],
            4: ["tracking"],
            5: ["enhanced_damage", "steal", "accounting"],
            6: ["second_attack"],
            7: ["sneak"],
            8: ["strangle"],
            9: ["rescue"],
            10: ["interrogate"],
            11: ["dual"],
            13: ["fast_healing"],
            14: ["lore"],
            15: ["debating"],
            16: ["third_attack"],
            19: ["self_discipline"],
            22: ["intimidate"],
            26: ["marksman"],
            31: ["ultra_damage"],
        },
    },
    "professor": {
        "nome": "Professore", "nome_originale": "Professor",
        "descrizione": "Un membro della facolta' della famosa Universita' Miskatonic ad "
                       "Arkham. Il processo di selezione e' severo: serve un livello avanzato di "
                       "conoscenza nel proprio campo di studi.",
        "attributo_primario": "int",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 4, 3, 2, 2, 3, 3))),
        "condizioni": {"livello": 30,
                       "skill": {"arkham": 60, "dissertation": 70, "education": 90},
                       "imprese": ["deed_56"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["atlantean", "debating", "stygian"],
            2: ["lore"],
            3: ["spell_casting"],
            5: ["enhanced_damage", "teach"],
            6: ["dream_magic"],
            7: ["cthonic"],
            10: ["second_attack"],
            11: ["meditation"],
            12: ["word_of_recall"],
            13: ["scribe"],
            14: ["fast_healing"],
            15: ["mayan"],
            16: ["know_alignment"],
            17: ["brew"],
            18: ["locate_object"],
            22: ["scrying"],
            25: ["clerical_magic"],
        },
    },
    "ranger": {
        "nome": "Ranger", "nome_originale": "Ranger",
        "descrizione": "Una persona addestrata al combattimento che vive e prospera nelle "
                       "vaste foreste selvagge delle Dreamlands, a disagio in citta'.",
        "attributo_primario": "dex",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (3, 3, 2, 3, 2, 2, 2))),
        "condizioni": {"livello": 30, "skill": {"education": 40, "ulthar": 60, "axe": 85},
                       "imprese": ["deed_84"]},
        "skill_per_livello": {
            0: ["english", "hand_to_hand"],
            1: ["bow", "dodge", "french", "gaelic", "second_attack", "traps", "world_geography"],
            2: ["cthonic", "dual", "hebrew", "strangle", "swim"],
            3: ["climb", "riding", "spear"],
            4: ["hide"],
            5: ["fast_healing", "tailor", "tame", "tracking"],
            6: ["biology"],
            7: ["sneak"],
            8: ["brawling"],
            9: ["detection", "whip"],
            10: ["forging", "third_attack"],
            11: ["peek"],
            12: ["circle", "survival"],
            13: ["sword"],
            14: ["axe_master"],
            15: ["frenzy", "lore", "spell_casting"],
            16: ["create_food"],
            17: ["create_spring"],
            18: ["cure_light"],
            19: ["control_weather", "martial_arts"],
            20: ["old_english"],
            21: ["ultra_damage"],
            22: ["body_control"],
            23: ["master_archer"],
            24: ["water_breathing"],
            25: ["call_lightning"],
            26: ["faerie_fire"],
            27: ["fly"],
            29: ["detect_hidden"],
            30: ["stygian"],
            34: ["summon_familier"],
            38: ["fourth_attack"],
            40: ["haste"],
        },
    },
    "scout": {
        "nome": "Esploratore", "nome_originale": "Scout",
        "descrizione": "Una persona che ha affinato varieta' di abilita' di tracciamento, "
                       "esplorazione, combattimento e criminalita'. Forte focus fisico, con un po' di istruzione.",
        "attributo_primario": "dex",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (3, 2, 2, 3, 2, 3, 1))),
        "condizioni": {"skill": {"education": 20, "hide": 30, "sneak": 30, "streetwise": 40, "ulthar": 40}},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["climb", "dagger", "dirt_kicking", "haggle", "hide", "kick", "mace", "search", "steal", "swim"],
            2: ["backstab", "parry", "sneak", "spanish"],
            3: ["circle", "pick_lock", "second_attack"],
            4: ["spear", "tracking"],
            5: ["detection", "rotate"],
            6: ["italian", "sword", "tame"],
            7: ["brawling"],
            8: ["peek", "romany"],
            9: ["enhanced_damage"],
            10: ["bow", "polish"],
            11: ["fast_healing"],
            12: ["accounting"],
            13: ["traps"],
            14: ["third_attack"],
            15: ["greek"],
            16: ["occult"],
            17: ["ultra_damage"],
            18: ["latin"],
            19: ["meditation"],
            20: ["lore"],
            22: ["riding"],
            25: ["tailor"],
            27: ["blackjack"],
        },
    },
    "soldier": {
        "nome": "Soldato", "nome_originale": "Soldier",
        "descrizione": "Una persona addestrata all'arte della battaglia, armata e "
                       "disarmata. Focus su abilita' fisiche e di combattimento.",
        "attributo_primario": "str",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (3, 2, 2, 3, 3, 3, 2))),
        "condizioni": {"skill": {"education": 30, "streetwise": 30, "arkham": 40}},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["dagger", "hide", "kick", "martial_arts", "parry", "search", "swim"],
            2: ["german", "handgun", "sneak", "strong_grip", "trip"],
            3: ["detection", "gun", "second_attack"],
            4: ["climb", "disarm", "enhanced_damage"],
            5: ["brawling", "strangle"],
            6: ["bash"],
            8: ["fast_healing"],
            10: ["dual"],
            11: ["rescue"],
            12: ["circle"],
            14: ["submachinegun"],
            15: ["rotate"],
            16: ["backstab"],
            18: ["ultra_damage"],
            22: ["third_attack"],
            26: ["traps"],
            30: ["machinegun"],
            55: ["artillery"],
            70: ["sniper"],
        },
    },
    "spirit_summoner": {
        "nome": "Evocatore di Spiriti", "nome_originale": "Spirit Summoner",
        "descrizione": "Uno Zoog maestro di magia con abilita' arcane altamente "
                       "addestrate. Forte focus su magia, occultismo e incantesimi.",
        "attributo_primario": "wis",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 3, 3, 3, 2, 4, 3))),
        "condizioni": {"razza": "zoog", "livello": 30,
                       "skill": {"spell_casting": 20, "occult": 30, "education": 60, "dreamlands": 70},
                       "imprese": ["deed_59", "deed_83", "deed_84"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["bow", "elemental_shield", "natural_magic", "stygian"],
            2: ["acid_breath", "astronomy", "create_spring", "meditation", "old_english", "scrolls"],
            3: ["ancient_geography", "ancient_history"],
            4: ["control_weather", "parry", "staves", "wands"],
            5: ["fire_breath", "lightning_breath"],
            6: ["detect_poison", "faerie_fire"],
            7: ["call_lightning", "detect_magic"],
            8: ["detect_invis", "enhanced_damage", "faerie_fog"],
            9: ["cure_poison", "search"],
            10: ["dispel_magic", "frost_breath", "lesser_possession"],
            11: ["continual_light", "detect_hidden"],
            12: ["frenzy"],
            13: ["sleep", "strength"],
            14: ["dual", "manipulation"],
            15: ["harden_skin", "water_breathing"],
            16: ["burning_hands", "identify"],
            17: ["lightning_bolt"],
            18: ["gas_breath", "stun_breath", "summon_familier"],
            19: ["armor", "greater_possession"],
            21: ["way_of_the_conjurer"],
            22: ["chaos_magic"],
            26: ["chain_lightning"],
            32: ["elemental_combat"],
        },
    },
    "squid_hunter": {
        "nome": "Cacciatore di Calamari", "nome_originale": "Squid Hunter",
        "descrizione": "Un guerriero Profondo altamente addestrato nell'arte della "
                       "battaglia. Focus su abilita' fisiche e di combattimento.",
        "attributo_primario": "str",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (3, 2, 2, 2, 3, 2, 1))),
        "condizioni": {"razza": "deep_one", "skill": {"innsmouth": 40, "spear": 70}, "imprese": ["deed_9061"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["axe", "hide", "kick", "parry", "martial_arts", "search", "shield_block", "strong_grip"],
            2: ["greek", "polearm", "sneak", "sword", "trip"],
            3: ["detection", "second_attack"],
            4: ["disarm", "enhanced_damage"],
            5: ["occult"],
            6: ["bash"],
            7: ["tracking"],
            8: ["fast_healing"],
            9: ["flail"],
            10: ["crush", "dual"],
            11: ["rescue"],
            12: ["circle", "climb"],
            13: ["latin"],
            14: ["ancient_history"],
            15: ["rotate"],
            16: ["backstab"],
            18: ["scrolls"],
            19: ["strangle"],
            20: ["ultra_damage"],
            22: ["third_attack"],
            23: ["handgun"],
            25: ["spear_master"],
            30: ["dagger_master"],
        },
    },
    "thief": {
        "nome": "Ladro", "nome_originale": "Thief",
        "descrizione": "Una persona che ha affinato le abilita' di rubare agli altri. "
                       "Focus fisico, con un po' di istruzione.",
        "attributo_primario": "dex",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (2, 2, 2, 3, 2, 3, 2))),
        "condizioni": {"skill": {"education": 30, "hide": 30, "sneak": 30, "streetwise": 30, "arkham": 40}},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["climb", "dagger", "dirt_kicking", "haggle", "hide", "kick", "mace", "search", "steal", "swim"],
            2: ["backstab", "german", "parry", "sneak"],
            3: ["circle", "handgun", "pick_lock", "second_attack"],
            4: ["world_affairs", "world_geography"],
            5: ["modern_history", "rotate"],
            6: ["italian"],
            7: ["gambling", "martial_arts"],
            8: ["peek", "polish"],
            9: ["enhanced_damage"],
            10: ["romany"],
            11: ["fast_healing"],
            12: ["accounting"],
            13: ["detection", "traps"],
            14: ["third_attack"],
            15: ["chemistry"],
            16: ["greek", "occult"],
            17: ["ultra_damage"],
            18: ["latin"],
            19: ["meditation"],
            20: ["lore"],
            25: ["assassinate"],
            30: ["blackjack"],
            45: ["forgery"],
        },
    },
    "warrior": {
        "nome": "Guerriero", "nome_originale": "Warrior",
        "descrizione": "Una persona ben addestrata nell'arte della battaglia, armata e "
                       "disarmata. Forte concentrazione su abilita' fisiche e di combattimento.",
        "attributo_primario": "str",
        "modificatori_attributi": dict(zip(ATTRIBUTI_ORDINE, (3, 2, 2, 3, 2, 2, 2))),
        "condizioni": {"skill": {"ulthar": 40, "streetwise": 60}, "imprese": ["deed_9061"]},
        "skill_per_livello": {
            0: ["dodge", "english", "hand_to_hand"],
            1: ["cthonic", "fast_healing"],
            2: ["blindness", "create_food", "elemental_shield"],
            3: ["create_spring", "lesser_possession", "old_english", "sword"],
            4: ["cancellation", "scrying", "second_attack"],
            5: ["mental_magic", "teach"],
            6: ["stygian"],
            7: ["debating"],
            8: ["harden_skin"],
            9: ["negate_alignment", "scribe"],
            10: ["call_lightning"],
            11: ["greater_possession"],
            12: ["calm"],
            13: ["mass_invis"],
            14: ["fireball"],
            16: ["summon_familier"],
            17: ["demonfire"],
            18: ["dagger_master"],
            19: ["haste"],
            21: ["pass_door", "absorb_magic"],
            24: ["spell_mastery"],
            25: ["ritual_mastery"],
            26: ["acid_breath"],
            29: ["chaos_magic"],
            30: ["summon"],
            31: ["gas_breath"],
            32: ["portal"],
            35: ["youth"],
            40: ["mask_self"],
            60: ["elemental_combat"],
            85: ["elder_magic"],
        },
    },
}


def nome_professione_avanzata(prof_id):
    entry = PROFESSIONI_AVANZATE.get(prof_id)
    return entry["nome"] if entry else prof_id


def valuta_condizioni(personaggio, prof_id):
    """Controlla se personaggio soddisfa le condizioni della professione
    avanzata prof_id. Ritorna (ok: bool, motivi_mancanti: list[str])."""
    entry = PROFESSIONI_AVANZATE.get(prof_id)
    if not entry:
        return False, ["Professione sconosciuta."]

    condizioni = entry["condizioni"]
    mancanti = []

    livello_richiesto = condizioni.get("livello")
    if livello_richiesto and personaggio.livello_personaggio() < livello_richiesto:
        mancanti.append(f"livello {livello_richiesto} (hai {personaggio.livello_personaggio()})")

    razza_richiesta = condizioni.get("razza")
    if razza_richiesta and personaggio.db.race != razza_richiesta:
        from world.races import nome_razza
        mancanti.append(f"razza {nome_razza(razza_richiesta)}")

    cult_richiesto = condizioni.get("cult")
    if cult_richiesto and personaggio.db.cult != cult_richiesto:
        mancanti.append(f"cult {cult_richiesto}")

    intervallo_allineamento = condizioni.get("allineamento")
    if intervallo_allineamento:
        minimo, massimo = intervallo_allineamento
        if not (minimo <= (personaggio.db.alignment or 0) <= massimo):
            mancanti.append(f"allineamento tra {minimo} e {massimo}")

    for skill_id, soglia in condizioni.get("skill", {}).items():
        rating = (personaggio.db.skills or {}).get(skill_id, 0)
        if rating < soglia:
            from world.skills import nome_skill
            mancanti.append(f"{nome_skill(skill_id)} {soglia}% (hai {rating}%)")

    imprese_richieste = condizioni.get("imprese", [])
    if imprese_richieste:
        from world.imprese import REGISTRO_IMPRESE

        imprese_fatte = personaggio.db.imprese or set()
        for impresa in imprese_richieste:
            if impresa not in imprese_fatte:
                titolo = REGISTRO_IMPRESE.get(impresa, (impresa,))[0]
                mancanti.append(f"impresa \"{titolo}\"")

    return not mancanti, mancanti
