"""
Nomi italiani dei 204 social (fase 4 della traduzione dell'interfaccia).

Stesso schema di world/comandi_italiano.py, e stesse ragioni: i nomi
inglesi restano validi, questi si affiancano. La tabella sta in un modulo
separato da world/socials.py di proposito - quello e' un file di
contenuto da 2972 righe trascritto dalla fonte, e non ha senso rischiare
di sporcarlo per aggiungere una parola per voce.

I social sono la parte piu' "di colore" del gioco: e' proprio li' che
scrivere ABBRACCIA invece di HUG cambia la sensazione di star giocando
in italiano. Per questo valeva la pena farli, benche' siano piu' numerosi
di tutti gli altri comandi messi insieme.

CRITERI DI TRADUZIONE
---------------------
- verbo all'imperativo quando il social e' un'azione (abbraccia, ridi);
- sostantivo quando in italiano suona piu' naturale del verbo
  (pernacchia, linguaccia, testata);
- le onomatopee e le sigle da chat senza un equivalente sensato
  ricevono comunque un nome italiano descrittivo (lol -> sbellicati,
  brb -> tornosubito), perche' un elenco meta' tradotto sarebbe peggio
  di entrambe le scelte pure;
- niente spazi: un alias con lo spazio funziona in Evennia ma confonde
  chi prova a indovinarlo.

Le collisioni con comandi e uscite sono controllate da
world/comandi_italiano.py:verifica_collisioni(), che legge anche questa
tabella.
"""

ALIAS_SOCIAL = {
    # --- prima tornata --------------------------------------------------
    "aargh": "sbraita",
    "accuse": "accusa",
    "apologize": "scusati",
    "applaud": "applaudi",
    "beg": "implora",
    "blush": "arrossisci",
    "boast": "vantati",
    "bow": "inchinati",
    "cheer": "esulta",
    "comfort": "conforta",
    "cry": "piangi",
    "dance": "balla",
    "glare": "fulmina",
    "grin": "sogghigna",
    "growl": "ringhia",
    "hug": "abbraccia",
    "kiss": "bacia",
    "laugh": "ridi",
    "nod": "annuisci",
    "pat": "pacca",
    "ponder": "rifletti",
    "poke": "punzecchia",
    "punch": "pugno",
    "salute": "saluta",
    "shrug": "spallucce",
    "sigh": "sospira",
    "slap": "schiaffeggia",
    "smile": "sorridi",
    "spit": "sputa",
    "thank": "ringrazia",
    "tickle": "solletica",
    "wave": "sventola",
    "wink": "occhiolino",

    # --- lettere A-H ----------------------------------------------------
    "adjust": "aggiustati",
    "air": "chitarraaria",
    "aroo": "inclinatesta",
    "babble": "farfuglia",
    "bark": "abbaia",
    "bat": "batticiglia",
    "bcatch": "afferrabirra",
    "bearhug": "stritola",
    "beckon": "faicenno",
    "beer": "birra",
    "bird": "ditomedio",
    "bitchslap": "schiaffone",
    "bkiss": "mandabacio",
    "bleed": "sanguina",
    "bling": "sfoggia",
    "blink": "sbattipalpebre",
    "boggle": "sbalordisci",
    "bonk": "colpetto",
    "booty": "saccheggia",
    "bounce": "saltella",
    "brat": "linguaccia",
    "brb": "tornosubito",
    "brush": "spazzola",
    "burp": "rutta",
    "cackle": "ghigna",
    "charge": "carica",
    "chuckle": "ridacchia",
    "clap": "battimani",
    "claw": "artiglia",
    "collapse": "crolla",
    "cough": "tossisci",
    "cover": "copriorecchie",
    "cower": "rannicchiati",
    "cringe": "ritraiti",
    "criticize": "critica",
    "cuddle": "coccola",
    "curse": "maledici",
    "curtsey": "riverenza",
    "daydream": "fantastica",
    "dogpile": "mucchio",
    "drool": "sbava",
    "duck": "abbassati",
    "embrace": "stringi",
    "eyebrow": "sopracciglio",
    "facepalm": "manoinfaccia",
    "faint": "svieni",
    "fart": "scoreggia",
    "flare": "divampa",
    "flash": "lampeggia",
    "flex": "flettimuscoli",
    "flinch": "sussulta",
    "flip": "capriola",
    "flirt": "flirta",
    "flog": "frusta",
    "flop": "stravaccati",
    "flutter": "svolazza",
    "frown": "aggrotta",
    "fsm": "spaghettovolante",
    "fume": "ribolli",
    "gasp": "trasecola",
    "giggle": "risatina",
    "goose": "pizzicasedere",
    "grats": "congratulazioni",
    "grimace": "smorfia",
    "groan": "gemi",
    "grovel": "striscia",
    "grumble": "brontola",
    "hand": "porgimano",
    "handshake": "stringimano",
    "headbutt": "testata",
    "hiccup": "singhiozza",
    "highfive": "cinque",
    "hop": "salta",
    "horn": "corna",
    "howl": "ulula",
    "hum": "canticchia",
    "hush": "zitto",

    # --- lettere I-Y ----------------------------------------------------
    "innocent": "innocente",
    "insane": "impazzisci",
    "jig": "giga",
    "knee": "ginocchiata",
    "laces": "lacci",
    "lightbulb": "lampadina",
    "lol": "sbellicati",
    "manicure": "manicure",
    "massage": "massaggia",
    "meditate": "medita",
    "moo": "muggisci",
    "moon": "chiappe",
    "mosh": "pogo",
    "mourn": "lutto",
    "mutter": "mormora",
    "noogie": "grattatesta",
    "nudge": "gomitata",
    "passout": "stramazza",
    "peck": "bacetto",
    "peer": "scruta",
    "pie": "torta",
    "pinch": "pizzica",
    "point": "indica",
    "pounce": "balzaaddosso",
    "pout": "imbronciati",
    "propose": "proponi",
    "puke": "vomita",
    "purr": "fusa",
    "pwn": "domina",
    "ramble": "divaga",
    "raspberry": "pernacchia",
    "rofl": "rotola",
    "roll": "occhialcielo",
    "rose": "rosa",
    "ruffle": "scompiglia",
    "run": "corri",
    "scream": "urla",
    "serenade": "serenata",
    "shake": "scuoti",
    "shiver": "rabbrividisci",
    "skip": "sgambetta",
    "slobber": "sbavaaddosso",
    "smirk": "ghignetto",
    "snap": "schiocca",
    "snarl": "digrigna",
    "sneeze": "starnutisci",
    "snicker": "sghignazza",
    "sniff": "annusa",
    "snore": "russa",
    "snort": "sbuffa",
    "snowball": "pallaneve",
    "snuggle": "accoccolati",
    "sob": "piangiforte",
    "squeal": "strilla",
    "squeeze": "stringiforte",
    "stagger": "barcolla",
    "stare": "fissa",
    "stretch": "stiracchiati",
    "strut": "pavoneggiati",
    "sulk": "broncio",
    "swoon": "struggiti",
    "tackle": "placca",
    "tag": "acchiappa",
    "tap": "picchietta",
    "threaten": "minaccia",
    "tip": "mancia",
    "twiddle": "tamburella",
    "type": "digita",
    "whine": "piagnucola",
    "whistle": "fischia",
    "wince": "trasali",
    "wonder": "meravigliati",
    "worry": "preoccupati",
    "yae": "evviva",
    "yawn": "sbadiglia",

    # --- categoria "sessuale" (vietata ai newbie, vedi world/socials.py) --
    # Registro allusivo e mai esplicito, come nella fonte: la traduzione
    # mantiene lo stesso tono, non lo alza.
    "caress": "accarezza",
    "fondle": "palpa",
    "french": "baciofrancese",
    "grope": "brancica",
    "lick": "lecca",
    "love": "ama",
    "lust": "brama",
    "moan": "gemito",
    "nibble": "mordicchia",
    "nuzzle": "strofinanaso",
    "pant": "ansima",
    "rub": "strofina",
    "spank": "sculaccia",
    "strip": "spogliati",
    "stroke": "carezza",
    "tease": "stuzzica",
    "tongue": "linguain",
    "undress": "svesti",
    "wiggle": "dimenati",
}
